### ISSUE TITLE
Benefit from static anlysis

### ISSUE THREAD

**Issue by szepeviktor** [terrylinooo/shieldon#12]
Please run `phpstan analyse src/ -l 0` and raise level one-by-one.

Powered by @phpstan

**Comment by szepeviktor** [comment]
On Level 0 one of solutions is suggesting `psr/http-message` and `psr/http-server-middleware` in composer.json and installing it before using PHPStan.

**Comment by szepeviktor** [comment]
Please do not stop until Level 4.

**Comment by terrylinooo** [comment]
I will take a look at the library you mention. Thanks for your suggestion.
