### ISSUE TITLE
Sesion Limit

### ISSUE THREAD

**Issue by emo44** [terrylinooo/shieldon#15]
Units in controllPanel for Sesion limits says Minute..so 300 minute or 300 seconds like in the image? I change onlineLimit to 2 and 1 unit keepalive and never shows the message when i test it..

**Comment by terrylinooo** [comment]
If you set keepalive to `1` means that the current session will be expired and Shieldon will open a new queue for the next visitor, so the situation you mention is normal. My suggestion is to set that value at least 5 minutes (300 seconds).
