### ISSUE TITLE
Website shieldon.io not available due to strict settings?

### ISSUE THREAD

**Issue by Boschman** [terrylinooo/shieldon#17]
This seems like a really nice project, but unfortunately I'm not able to reach the website https://shieldon.io/. No matter what IP address I use (and I've tried at least 10 different IPs), I always get this message:

`The IP address you are using has been blocked.`

Could it be that the WAF has been configured a bit too strict?

I'd really like to give this project a try, but I need access to the website to be able to read the documentation.

Any help is appreciated.

**Comment by terrylinooo** [comment]
Did you use proxy or VPN ips?
IP address from proxy or VPN often do not have setReverse DNS, so that RDNS strict mode will deny such kind of request. I have turned it off, you can try again.

**Comment by Boschman** [comment]
Yes, I can reach the website now! Thanks!

I don't use a proxy or VPN. My IP address has a PTR record, so I don't think a missing reverse-DNS could have caused the problem. If you would like to investigate the situation, I could share my IP address with you via a private message. Just let me know.

**Comment by terrylinooo** [comment]
You can ping the reversed hostname of your IP address. It should be return your IP string. If not, the RDNS strict mode of Shieldon will deny the request.

**Comment by Boschman** [comment]
Your site is unavailable again. Have you changed anything?

My IP has got a fully qualified PTR record, so there's no problem on my side. I never had any problems with visiting websites; your site is the first. I think you should really reconsider your strict policy. You're blocking legitimate visitors.

And I really would like to read the documentation so I can start using this project :-)
Would be great if you could help me.

**Comment by terrylinooo** [comment]
What is your IP address you used to visit that website. Send them to my email then I can figure out what casues the problem. By the way, fully qualified PTR record must have pointed the correct A record on it.

For example:
![image](https://user-images.githubusercontent.com/11989371/75092075-41cfda00-55af-11ea-8902-2675291de3b8.png)

IP is not matched with reversed hostname:

![image](https://user-images.githubusercontent.com/11989371/75092087-72177880-55af-11ea-96f5-fc97ec324462.png)

Is your IP on the list?

![image](https://user-images.githubusercontent.com/11989371/75092120-c7538a00-55af-11ea-9c63-327bcdd3b5a3.png)

Can you paste your request header information, for example: on your chrome browser, press F12, find the information such as below:

![image](https://user-images.githubusercontent.com/11989371/75092163-27e2c700-55b0-11ea-82c4-4d7ae7c058c5.png)
