### ISSUE TITLE
How to enable or white list google bots?

### ISSUE THREAD

**Issue by darjus01** [terrylinooo/shieldon#20]
Hi, I accedently block out google bosts crawler. how to whitelist it? I tried to use Firewall > Components > Trusted Bots. but it not enabling after save. I find no instructions how to manage this.
Please help ASAP.

**Comment by terrylinooo** [comment]
Hello. You have to make sure the folder in where the configuration file is writable, or the saving setting will not work.

To whitelist Google bot is here.
![image](https://user-images.githubusercontent.com/11989371/82452634-1db66300-9ae2-11ea-91bb-df40dff4d8d8.png)

**Comment by darjus01** [comment]
I have checked config file "trusted_bot":{"enable":true,"strict_mode":false,"allow_list":[]}
but is off 
![image](https://user-images.githubusercontent.com/10930096/82453841-b84e7c00-9ab9-11ea-84ed-4a62ed891096.png)

**Comment by terrylinooo** [comment]
What version are you using?

**Comment by darjus01** [comment]
"shieldon/shieldon": "^1.0",

**Comment by terrylinooo** [comment]
Try to update Shieldon to 1.0.3 might be helpful.
```
 composer update shieldon/shieldon
```

**Comment by darjus01** [comment]
updated it and resaved it saved, I have here lots of google clawlers blocked I need to delte it by and or it will onblock them?
![image](https://user-images.githubusercontent.com/10930096/82460944-82fa5c00-9ac2-11ea-858d-57d46328d971.png)

**Comment by terrylinooo** [comment]
You can reset the data by clicking the button as below screenshot and start a new data circle.

![image](https://user-images.githubusercontent.com/11989371/82465963-6aa23580-9af2-11ea-964e-3fbdfe73e7a4.png)
