### ISSUE TITLE
IP Blocked problem | Access Denied

### ISSUE THREAD

**Issue by iamtortue001101** [terrylinooo/shieldon#23]
Hello!

I made a wrong setting and it remained that way.
![Screenshot_3](https://user-images.githubusercontent.com/46280838/85933294-21f24f00-b8de-11ea-91ce-b4c2f40aee06.png)

I use codeigniter as the PHP library.
Although I installed it from scratch, this problem does not improve. I connect from a different network, but it's still the same.

**Comment by terrylinooo** [comment]
1. Try to disable Header component.  This problem may happen when your request header to that page doesn't contain `Accept` header information because of browser's cache.

2. Turn of `strict mode` in components.

I will add a message code in that page to point out the reason of blocking.
Thanks for your reporting.

**Comment by iamtortue001101** [comment]
> 1. Try to disable Header component.  This problem may happen when your request header to that page doesn't contain `Accept` header information because of browser's cache.
> 2. Turn of `strict mode` in components.
> 
> I will add a message code in that page to point out the reason of blocking.
> Thanks for your reporting.

Unfortunately, it didn't work. I also cleared browser cookies.

![Screenshot_4](https://user-images.githubusercontent.com/46280838/85941971-f9467580-b92e-11ea-985d-ab1cd48715e9.png)

**Comment by iamtortue001101** [comment]
It worked when I changed this place. Where can I find this file?

![image](https://user-images.githubusercontent.com/46280838/85942247-d3ba6b80-b930-11ea-8581-b28dc8419e1f.png)

**Comment by iamtortue001101** [comment]
I think I found the problem. When I turn this on, it blocks all IP addresses.

![image](https://user-images.githubusercontent.com/46280838/85942770-12055a00-b934-11ea-87ab-a4852b79c05a.png)

**Comment by Anfal95** [comment]
I have the same problem, I have turned off the strict mode but it didn't work
