### ISSUE TITLE
Messenger not working

### ISSUE THREAD

**Issue by AlexLightning** [terrylinooo/shieldon#24]
I've installed this on a Laravel app (v7) following your guide. The problem is that after I click "Test" for example for SlackWeebHook nothing seems to happen. It keeps loading. I figured out there must be a problem, looked in the config and changed the "confirm_test" value to true and I get the message: "Class 'Messenger\SlackWebhook' not found". Any idea?

**Comment by terrylinooo** [comment]
Just fixed this issue. Please update to 1.0.4
Thanks for reporting.
