### ISSUE TITLE
Pagination problem in Demo page

### ISSUE THREAD

**Issue by Quirinus** [terrylinooo/shieldon#27]
Pagination doesn't have:
- space between "buttons"
- any styles applied to make it more obvious (like link underlines, bold style, etc.)

It appears as this to me:
Previous123Next

The "buttons" work correctly though, so it's a matter of appearance and formatting.

I'm not sure if this is just a Demo page issue, or an issue with Shieldon.

**Comment by terrylinooo** [comment]
Thanks. I will check this issue later.

**Comment by terrylinooo** [comment]
Shieldon has been updated to 2.0.1.
Thank you very much.
