### ISSUE TITLE
Control panel language problems

### ISSUE THREAD

**Issue by Quirinus** [terrylinooo/shieldon#28]
I'll list some of the language problems in the demo control panel. There's more things that could be changed, but I don't know the context well enough to do so, so I'll just list the ones that I'm sure of. I checked just the pages until, and including, Firewall > Settings > Daemon.

### Status > Firewall

- Check whether visitors can create cookie by JavaScript. --> Check whether visitors can create cookies with JavaScript.
- Detect whether multiple sessions created by the same visitor. --> Detect whether multiple sessions were created by the same visitor.
- Check how often does a visitor view the pages. --> Check how often a visitor views pages.
- Allow popular search engines crawl your website. --> Allow popular search engines to crawl your website.
- Analyze header information from visitors. -->Analyze visitor header information.
- Identify IP resolved hostname (RDNS) from visitors. --> Identify visitor IP resolved hostname (RDNS).
- Analyze user-agent information from visitors. --> Analyze visitor user-agent information.

### Status > Operation

- Check whether visitors can create cookie by JavaScript. --> Check whether visitors can create cookies with JavaScript.
- Detect whether multiple sessions created by the same visitor. --> Detect whether multiple sessions were created by the same visitor.
- Check how often does a visitor view the pages. --> Check how often a visitor views pages.
- Block requests by the rules set by IP Manager. --> Block requests using the rules set in the IP Manager.
- Block requests which are identified as fake search engine. --> Block requests which are identified to be from fake search engines.
- Block requests without RDNS record. --> Block requests without a RDNS record.

### Data Circle > IP Rules
_I've never seen "circle" and "cycle" used like this, there should be some other, more traditional words used for this, but they escape me for now._
- It is the place where the Shieldon temporarily allows or denies users in the current cycle. --> Shieldon temporarily allows or denies access to users in this table. _(I removed the cycle reference, since it's mentioned below.)_
- All processes are automatic and instant, you can ignore that. _(What does this mean? It can all probably be removed, or at least the "you can ignore that" part.)_
- Rule table will be reset when new cycle begins. --> Rule table will be reset when a new cycle begins.
- Identified as fake search engine. --> Identified as a fake search engine.
- Secondly limit reached. --> Secondary limit reached.

### Data Circle > Sessions
- Keep-alive period. (minutes) --> Keep-alive period (in minutes).
- Online user amount. --> Online user count.
- Read-time logs for Online Session Controll. --> Real-time logs for Online Session Control. _(Did you mean to say "real-time"?)_
- All processes are automatic and instant, you can ignore that. _(Same as before, what does this mean? Remove all or just the last part.)_
- Notice this is only working when you have enabled that function. --> **Notice**: this only works when enabled.

Table headers:
- Time _(This can be changed to "Start" or "Created" to make it clearer.)_
- Remain Seconds --> Seconds Remaining

### Firewall > Settings > Daemon

**Enable**
- Not recommended for high-traffic website. --> Not recommended for high-traffic websites.
- Is your website behind the CDN service? --> Is your website behind a CDN service?

**Session Limit**
- When the online user amount has reached the limitation, other users not in the queue have to line up! --> When the number of users online has reached the limit, users that are not in the queue have to line up!
- The maximum amount of online user. --> The maximum number of users online.
- Users with multiple sessions will be kicked off. --> Users with multiple sessions will be kicked.

**Action Logs**
- Not recommended for high-traffic website. --> Not recommended for high-traffic websites.

**System Firewall**
- Make sure you have installed iptables and ip6tables already in your server, and employ iptables_bridge.sh in crontab correctly. --> Make sure you have iptables and ip6tables already installed on your server, and employ iptables_bridge.sh in crontab correctly.
- Watching Folder --> Watch Folder
- Please use this code into the crontab file on your server. --> Please insert this code into the crontab file on your server.
- iptables_bridge.sh will watch the changes in this folder to employ command to iptables. --> iptables_bridge.sh will watch the changes in this folder to employ commands to iptables.
- Please move iptables_bridge.sh to a safe place that only you know, changing the path for security reason. -->Please move iptables_bridge.sh to a safe place only accessible to you, changing the path for security reasons.

**Deny Attempts**
- Say goodbye to bad behavior visitors. --> Say goodbye to badly behaved visitors.
- A larger value of this filed means more strict. --> A larger value of this filed is more strict.
- Ban a user permanently in current data cycle. -->Ban user in current data cycle
- This event is triggered typically when a user fails too many times due to invalid CAPTCHA in a row. --> This event is typically triggered when a user fails too many CAPTCHAs in a row.
- Ban a user permanently in system firwall --> Permanently ban user in system firewall
- This event is triggered typically when a user is already banned permanently in curent data cycle, but they are still access the warning pages too many times in a row, we can confirm that they are malicious bots. --> This event is typically triggered when a user is already banned in the current data cycle, but they still access the warning pages too many times in a row - we can conclude that they are malicious bots.

**Comment by terrylinooo** [comment]
Thank you. I will update them later.

**Comment by terrylinooo** [comment]
Shieldon has been updated  to 2.0.1.
Thank you very much.
