### ISSUE TITLE
Can I test on localhost?

### ISSUE THREAD

**Issue by jfzanato** [terrylinooo/shieldon#29]
I'm using Laragon on localhost and pretty url enable, so I can open my https://shieldon.test/ with no erros.
But I can't open https://shieldon.test/firewall/panel/ because I receive a 404 error not found.

My code is:

```
<?php 

require_once(__DIR__.'/vendor/autoload.php');

$shieldon = new \Shieldon\Firewall\Integration\Bootstrap();
$shieldon->run();
```
What A'm I doing wrong?

**Comment by terrylinooo** [comment]
Hello. I don't know about Laragon, but URL rewrite is required to use Shieldon.

**Comment by jfzanato** [comment]
Hello!
Laragon is like XAMPP, localhost development.
If I setup rewrite with XAMPP, it should work?

**Comment by terrylinooo** [comment]
> Hello!
> Laragon is like XAMPP, localhost development.
> If I setup rewrite with XAMPP, it should work?

Yes. It will.

**Comment by Lucisu** [comment]
I was with this same issue, just use the `/` at the end of the URL:

`http://localhost/firewall/panel/`
