### ISSUE TITLE
CodeIgniter 3 Implementation - Error

### ISSUE THREAD

**Issue by lucdaduke** [terrylinooo/shieldon#34]
Initialized per instructions
An uncaught Exception was encountered
Type: InvalidArgumentException

Message: Unsupported HTTP protocol version number. "1.0" provided.

Filename: /vendor/shieldon/psr-http/src/Psr7/Message.php

Line Number: 483

**Comment by craiglondon** [comment]
@lucdaduke this probably has been resolved by this commit https://github.com/terrylinooo/psr-http/commit/c1c88c5979f3a477183c6c7712ed7648588f655c
