### ISSUE TITLE
小心enphp...

### ISSUE THREAD

**Issue by c2xusnpq6** [terrylinooo/shieldon#41]
https://enphp.djunny.com/

https://github.com/djunny/enphp

**Comment by terrylinooo** [comment]
什麼意思?

**Comment by c2xusnpq6** [comment]
怕shieldon不會擋`經enphp`的木馬...

`經enphp的b374k:`
[magic.zip](https://github.com/terrylinooo/shieldon/files/6097178/magic.zip)

https://www.virustotal.com/gui/file/db069fb498469425e1b38abc4bbb32224d9ef0e08248b844de6c5807a44e246c/detection

![image](https://user-images.githubusercontent.com/75058881/110241479-015db700-7f8c-11eb-8334-a96104ccb13b.png)

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/110241496-2b16de00-7f8c-11eb-85b5-2f863bf547bc.png)
https://www.virustotal.com/gui/file/bdb35b2c8b389ac35e5fcda1c71d2c8748b7e8ff0978793fc5aa74fc4a7c27f9/detection

**Comment by terrylinooo** [comment]
沒關係喔。Shieldon 不是防毒。是偵測網頁 request 的異常，主要擋暴力攻擊和惡意爬蟲。不過還是謝謝您的提醒。

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/110241664-e3dd1d00-7f8c-11eb-95e9-180867a8908d.png)

**Comment by c2xusnpq6** [comment]
就是怕用户上傳經enphp的木馬.....

**Comment by terrylinooo** [comment]
關於掃描上傳檔案這個功能，我再研究看看或許可加入第三方的防毒掃描 API 作為進階功能。
謝謝您的建議。有進一步的消息我再回覆在這篇貼文。

**Comment by c2xusnpq6** [comment]
連eset, bitdefender都不會顯示`suspicious`/`經混淆`的超超超強木馬?.............

**Comment by c2xusnpq6** [comment]
eset, bitdefender我都跟他們講了

您這邊進展如何?
