### ISSUE TITLE
Installation fails due an uppercase error

### ISSUE THREAD

**Issue by alejivo** [terrylinooo/shieldon#47]
Hi i trying to install it using composer and seems it doesn't work as its haves an case error in the 147 line:

In RootPackageLoader.php line 147:

  require.dirkgroenen/Pinterest-API-PHP is invalid, it should not contain uppercase characters. Please use dirkgroenen/pinterest-api-php instead.

**Comment by SpecialEdCT** [comment]
got similar error when trying to follow the instructions for codeigniter...

  [RuntimeException]                                                                                                             
  require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead.
