### ISSUE TITLE
Class "Shieldon\Firewall\Panel\iptables" not found

### ISSUE THREAD

**Issue by niyazialpay** [terrylinooo/shieldon#50]
I'm getting error when I enter the iptables page, may you check it please?

**Comment by niyazialpay** [comment]
I changed src/Firewall/Panel.php line 150 like below and issue has been fixed. 

$controller = __CLASS__ . '\\' . ($controller=="iptables"?"Iptables":ucfirst($controller));

May you update composer library?

**Comment by terrylinooo** [comment]
I will check it on this weekend. Thanks for reporting.
