### ISSUE TITLE
Activating plugin create issue with 'Save Draft' feature in Wordpress.

### ISSUE THREAD

**Issue by sparshrestha** [terrylinooo/shieldon#6]
Steps to reproduce:
Activate plugin > Add New Post > Save Draft
It produces "Updating failed" error and doesn't allow any draft to be saved.

![Screenshot from 2019-11-03 01-35-49](https://user-images.githubusercontent.com/15346503/68076245-4abb5680-fdda-11e9-8802-cbea65ca0a20.png)

**Comment by terrylinooo** [comment]
Updating to 1.4.2 will solve this issue. Thanks for reporting.
