### ISSUE TITLE
WAF rules

### ISSUE THREAD

**Issue by szepeviktor** [terrylinooo/shieldon#8]
Hello @terrylinooo !

In the last 5 years I was watching access logs and analyzing POST body dumps.
The result is 60+ rules.

- https://github.com/szepeviktor/waf4wordpress/tree/master/http-analyzer
- https://github.com/szepeviktor/waf4wordpress/tree/master/core-events

They are implemented in only 2 PHP files starting here
https://github.com/szepeviktor/waf4wordpress/blob/master/http-analyzer/waf4wordpress-http-analyzer.php#L322

I hope you benefit from them!

**Comment by terrylinooo** [comment]
It is valuable information. Thank you so much.
