### ISSUE TITLE
little error in doc for symfony

### ISSUE THREAD

**Issue by NodokaMurmevent** [terrylinooo/shieldon#9]
Hello i installed shieldon on symfony 4.4 and i had this error 
```
Notice: Undefined variable: csrfValue
```

i replaced in the controller
``` PHP
$controlPanel->csrf('_token', $token);
```
with 
``` PHP
$controlPanel->csrf('_token', $token->getValue());
```
no more the big error but now i just have the http login form always following by this message : "Permission required."

**Comment by terrylinooo** [comment]
The default login user is `shieldon_user` and the password is `shieldon_pass`.

If your web server is Apache, try:
https://stackoverflow.com/questions/9779552/http-authentication-with-php-not-working

**Comment by NodokaMurmevent** [comment]
ok it's work, but now it's a problem with the path on windows, 

if i `dump($configFilePath);` in vendor\shieldon\shieldon\src\Shieldon\Firewall.php Line 87
it's return me :
`"R:\server-web\folder\var\shieldon/config.firewall.json"`
(bad / )
later i will try later on linux. i will open another issue if needed
